<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>HangUp.App</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <ApplicationIcon>assets\handup.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="assets\*.ico" />
    <EmbeddedResource Include="assets\*.png" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\HangUp.Core\HangUp.Core.csproj" />
  </ItemGroup>
</Project>